### ISSUE TITLE
docs.skygear.io not indexed by google

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-doc#428] opened 2017-01-17 11:42 UTC
The [Get Started](https://docs.skygear.io/guide/get-started/js/) guides seems not indexed by Google.

[Searching for specify phrases](https://www.google.com.hk/search?q=site%3Adocs.skygear.io+%22Installing+and+running+the+scaffolding+generator%22) on google.com returns outdated content.

If content is not indexed by Google, the content basically doesn’t exist on the Internet.

**Comment by chpapa** [comment] 2017-01-19 11:06
Updated the title as suggested by @rickmak The problem is the new generated doc have no content. It should be fixed and revert to behave as old version

**Comment by bensonby** [comment] 2017-01-23 04:02
It is currently indexed by Google. The real issue should be #431. The old results appear before the new site. I tried a few different keywords and it showed the same behavior

<img width="676" alt="screen shot 2017-01-23 at 12 01 10" src="https://cloud.githubusercontent.com/assets/246195/22191218/aeccb8bc-e163-11e6-8d8c-3a9da5022624.png">


<img width="674" alt="skygear-get-started-google" src="https://cloud.githubusercontent.com/assets/246195/22191041/73616f26-e162-11e6-9aca-59df1eb1224b.png">

**Closed by bensonby** 2017-01-23 04:02 UTC
Labels: Code, Writing Doc
